### ISSUE TITLE
Action items for Sep 29, 2016 meeting

### ISSUE THREAD

**Issue by kaustavdm** [MozillaIndia/meta#1]
- [ ] Draft a blog post to announce the current state of the provisional meta team
- [ ] Draft up a proposal for criteria for joining the Meta team
- [ ] Infrastructure related things

**Comment by asdofindia** [comment]
Has there been a blog post about the meetup yet?

**Comment by kaustavdm** [comment]
@asdofindia Probably not. The docs team had sent out an elaborate email with the items. Probably worth putting as a blog post.

**Comment by asdofindia** [comment]
But that email was sent only to participants right?

**Comment by kaustavdm** [comment]
@asdofindia ah yes, good point.

**Comment by asdofindia** [comment]
I'm closing this as this isn't relevant any more and partly covered in newer issues.
