### ISSUE TITLE
Tasklists for restarting the restructure

### ISSUE THREAD

**Issue by psubhashish** [MozillaIndia/meta#6]
## Restructuring process
- [x] **Dec 1:** Announcement about the process and welcoming more members to join the meta team
- [x] **Dec 1:** RFC starts.
- [x] **Dec 13:** Closure of the first phase of RFC
- [x] **Dec 24:** All the RFCs on GitHub
- [x] **Dec 24:** Deciding about functional teams and publicly enlisting all the team lists and tagging them into the geographical groups.
- [ ] **Dec 27:** Create and share a form template that the functional teams will use to recruit new members

**Comment by asdofindia** [comment]
RFC on?

**Comment by kaustavdm** [comment]
@asdofindia RFC on meta team formation IIRC. Opening up the forum for broader participation.

**Comment by asdofindia** [comment]
I'm closing this @psubhashish because I think it has served its purpose. If I'm wrong, please reopen.
